name: .NET 9 CI

on:
  push:
    branches: [ main ]
    paths:
      - 'MinimalTodos.API/**/*.cs'
      - 'MinimalTodos.Tests/**/*.cs'
      - 'MinimalTodos.API/**/*.csproj'
      - 'MinimalTodos.Tests/**/*.csproj'
      - '.github/workflows/dotnet.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'MinimalTodos.API/**/*.cs'
      - 'MinimalTodos.Tests/**/*.cs'
      - 'MinimalTodos.API/**/*.csproj'
      - 'MinimalTodos.Tests/**/*.csproj'
      - '.github/workflows/dotnet.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore MinimalTodos.sln

      - name: Build
        run: dotnet build MinimalTodos.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test MinimalTodos.sln --no-build --configuration Release --verbosity normal
